language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - node_modules
install:
  - "npm install"
  - "./node_modules/.bin/judge install $JUDGE_CASE --overwrite"
env:
  - "JUDGE_CASE=gulp-tslint-5"
  - "JUDGE_CASE=gulp-tslint-6"
  - "JUDGE_CASE=gulp-tslint-7"
